### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by cmaumet** [xroll174/pipelines#10]
Hi @xroll174! I've just done a pass on your code and I really like the clarity of the codebase and the comments you've included, congrats! 

You will find below a few suggestions and comments. While you are looking into this, it would be great if you can send me a few example files (see below) and I'll double check the onsets/contrasts/design matrix more carefully. 

# General notes

*   Each time we use `spm_jobman('run',matlabbatch);` (e.g. in [first_level_analysis_octave.m#L136](https://github.com/xroll174/pipelines/blob/master/src/src/first_level_analysis_octave.m#L136)), let’s save the matlabbatch variable to disk with: `save(PATH_TO_FILE, 'matlabbatch'); `(this will be useful if we want to inspect one of the scripts later on) 

## Preprocessing

*   Can you give me an example of file created by mp_diffpow24.sh?
*   Is [first_level_analysis_octave_2.m](https://github.com/xroll174/pipelines/blob/master/src/src/first_level_analysis_octave_2.m) still in use? If not let’s delete it.
*   Can you send me an example of HCP EV file (e.g. lf.txt)? [extract_ev_octave.m#L11](https://github.com/xroll174/pipelines/blob/master/src/src/extract_ev_octave.m#L11) 
*   When you rerun an analysis do you delete all the data for all subjects? If not -- we might end up in an unstable state where the first step is redone (e.g. realign) but not the following (e.g. normalize). 
*   Remove this comment : [https://github.com/xroll174/pipelines/blob/master/src/src/preprocessing_octave.m#L3-L4](https://github.com/xroll174/pipelines/blob/master/src/src/preprocessing_octave.m#L3-L4) ?
*   Comment [here](https://github.com/xroll174/pipelines/blob/master/src/src/preprocessing_octave.m) should be moved above the call to mp_diffpow24.sh.

## First-level analyses

*   Add thresholding in first-level analyses (this will be useful for quality control)
*   Compute both contrasts as part of the same analysis (`matlabbatch{3}.spm.stats.con.consess{2})`: [first_level_analysis_octave.m#L136](https://github.com/xroll174/pipelines/blob/master/src/src/first_level_analysis_octave.m#L136). Once this is done we should no longer need fla_{parameter values}_list_hand_fsl_IGRIDA.sh? (This will bring more consistency with the code later in which con_0002 has to be the ‘right hand’ contrast.

## README

*   “/” missing in “.src” in “.src/bash_scripts/spmpath.txt” in the README
*   In “Dependencies and setup”, can we remove “Additionally, the paths to the folder containing the functions was stored in ./src/bash_scripts/srcpath.txt.” ? A person trying to reproduce your work does not need to edit this part, right?

# Links when reading through the code

**Preprocessing**. Entry point: [preprocessing_5_list_IGRIDA.sh](https://github.com/xroll174/pipelines/blob/master/src/bash_scripts/preprocessing_5_list_IGRIDA.sh)

*   [preprocessing_5_list.sh](https://github.com/xroll174/pipelines/blob/master/src/bash_scripts/preprocessing_5_list.sh) 
    *   [preprocessing_octave.m](https://github.com/xroll174/pipelines/blob/master/src/src/preprocessing_octave.m) 

**First-level analysis**. Entry point: [fla_5_0_0_list_IGRIDA.sh](https://github.com/xroll174/pipelines/blob/master/src/bash_scripts/fla_5_0_0_list_IGRIDA.sh)

*   [fla_5_0_0_list.sh](https://github.com/xroll174/pipelines/blob/master/src/bash_scripts/fla_5_0_0_list.sh) 
    *   [first_level_analysis_octave.m](https://github.com/xroll174/pipelines/blob/master/src/src/first_level_analysis_octave.m) 
        *   [extract_ev_octave.m](https://github.com/xroll174/pipelines/blob/master/src/src/extract_ev_octave.m) 
            *   [extract_ev_octave.m#L11](https://github.com/xroll174/pipelines/blob/master/src/src/extract_ev_octave.m#L11) 

**Second-level analysis**. Entry point: [second_level_analysis_full_hand_spm_IGRIDA.sh](https://github.com/xroll174/pipelines/blob/master/src/bash_scripts/second_level_analysis_full_hand_spm_IGRIDA.sh) 

*   [second_level_analysis_param_hand_size_corr.sh](https://github.com/xroll174/pipelines/blob/master/src/bash_scripts/second_level_analysis_param_hand_size_corr.sh) 
    *   [second_level_analysis_octave_mult_hand_size_corr.m](https://github.com/xroll174/pipelines/blob/master/src/src/second_level_analysis_octave_mult_hand_size_corr.m) 
        *   [second_level_analysis_octave_hand_corr.m](https://github.com/xroll174/pipelines/blob/master/src/src/second_level_analysis_octave_hand_corr.m)

**Comment by xroll174** [comment]
All the issues in the review have been taken into account.
